sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  - set -e

jobs:
  include:
    - stage: test
      script: if .travis/build-condition.sh "eq-author"; RAN_AUTHOR=true; pushd $PROJECT; ./scripts/ci.sh; popd; fi
    - script: if .travis/build-condition.sh "eq-author-api"; pushd $PROJECT; ./scripts/ci.sh; popd; fi
    - script: if .travis/build-condition.sh "eq-publisher"; pushd $PROJECT; ./scripts/ci.sh; popd; fi
    - script: if .travis/build-condition.sh "eq-author-graphql-schema"; pushd $PROJECT; ./scripts/ci.sh; popd; fi
    - stage: e2e 
      script: e2e/script/ci.sh

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master
    condition:
      - RAN_AUTHOR = true

branches:
  only:
    - master