sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  - set -e

jobs:
  include:
    - stage: test
      script:
        - pushd eq-author; ./scripts/ci.sh; popd;
        - pushd eq-author-api; ./scripts/ci.sh; popd;
        - pushd eq-publisher; ./scripts/ci.sh; popd;
    - stage: cypress
      script:
        - cd eq-author
        - yarn test:integration
        - yarn test:e2e
    - stage: cypress
      script:
        - cd eq-author
        - yarn test:integration
        - yarn test:e2e

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master

branches:
  only:
    - master
