sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "latest" ]; then echo "Building branches named latest not allowed as it would overwrite the stable docker image. Please rename your branch." && exit 1; fi;
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export TAG=${TAG//\//-}
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - echo "TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  - echo "TAG=$TAG"

script:
  - pushd eq-author; ./scripts/ci.sh; popd;
  - pushd eq-author-api; ./scripts/ci.sh; popd;
  - pushd eq-publisher; ./scripts/ci.sh; popd;
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push onsdigital/eq-author:$TAG
  - docker push onsdigital/eq-author-api:$TAG
  - docker push onsdigital/eq-publisher:$TAG

branches:
  only:
    - master
