sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

matrix:
  include:
    - env: PROJECT=eq-author
    - env: PROJECT=eq-author-api
    - env: PROJECT=eq-author-graphql-schema
    - env: PROJECT=eq-publisher

before_script:
  - set -e

script:
  - if .travis/build-condition.sh $PROJECT; then BUILD_SKIPPED=false; echo "$PROJECT is being built"; pushd $PROJECT; ./scripts/ci.sh; popd; else echo "$PROJECT is NOT being built"; BUILD_SKIPPED=true; fi
  - cd eq-author && yarn && yarn test:e2e

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master
    condition:
      - $PROJECT = eq-author
      - $BUILD_SKIPPED = false

branches:
  only:
  - master