sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

jobs:
  include:
    - stage: test
      script: .travis/run.sh "eq-author"
    - script: .travis/run.sh "eq-author-api"
    - script: .travis/run.sh "eq-publisher"
    - script: .travis/run.sh "eq-author-grapql-schema"
    - stage: e2e 
      script: e2e/script/ci.sh

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master
    condition:
      - RAN_AUTHOR = true

branches:
  only:
    - master