sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  - set -e

jobs:
  include:
    - stage: test
      script: eq-author/script/ci.sh
      if: .travis/build-condition.sh "eq-author" 
    - script: eq-author-api/script/ci.sh
      if: .travis/build-condition.sh "eq-author-api" 
    - script: eq-publisher/script/ci.sh
      if: .travis/build-condition.sh "eq-publisher" 
    - script: eq-author-graphql-schema/script/ci.sh
      if: .travis/build-condition.sh "eq-author-graphql-schema" 
    - stage: e2e 
      script: e2e/script/ci.sh

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master
    condition:
      - .travis/build-condition.sh "eq-author" 

branches:
  only:
  - master