sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
     - ~/.cache
     - $HOME/docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_script:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "latest" ]; then echo "Building branches named latest not allowed as it would overwrite the stable docker image. Please rename your branch." && exit 1; fi;
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export TAG=${TAG//\//-}
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - echo "TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  - echo "TAG=$TAG"

script:
  - yarn --frozen-lockfile
  - node_modules/.bin/prettylint "**/*.js" --ignore-path .gitignore
  - pushd eq-author; ./scripts/ci.sh; popd;
  - pushd eq-author-api; ./scripts/ci.sh; popd;
  - pushd eq-publisher; ./scripts/ci.sh; popd;
  - cd eq-author
  - yarn test:integration
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push onsdigital/eq-author:$TAG
  - docker push onsdigital/eq-author-api:$TAG
  - docker push onsdigital/eq-publisher:$TAG

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

branches:
  only:
    - master
    - speed-up-ci
