sudo: false

git:
  depth: false

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  yarn: true

script:
  - cd eq-author
  - yarn
  - yarn test:integration

deploy:
  local_dir: eq-author/storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master

branches:
  only:
    - master
