steps:
  - name: "node:10-alpine"
    env:
      - BABEL_ENV=test
      - NODE_ENV=test
      - PUBLIC_URL=test
      - CI=true
    args:
      - "-c"
      - |
        apk add jq bc
        yarn --frozen-lockfile
        cd eq-author
        yarn --frozen-lockfile
        yarn lint
        yarn test --coverage
        [ $? -eq 0 ]  || exit 1
        export percent=$(jq .total.lines.pct coverage/coverage-summary.json)
        echo "************************"
        echo "Target coverage: $_COVERAGE_LEVEL%"
        echo "************************"
        echo "************************"
        echo "Coverage: $percent%"
        echo "************************"
        export result=$(echo "$percent > $_COVERAGE_LEVEL" | bc)
        exit $(( 1 - $result ))
    id: unit_tests
    entrypoint: /bin/ash
timeout: 1200s
options:
  machineType: E2_HIGHCPU_8
