steps:
  - name: 'node:10'
    env:
      - BABEL_ENV=test
      - NODE_ENV=test
      - PUBLIC_URL=test
      - CI=true
    args:
      - '-c'
      - |
        apt update
        apt install -y jq bc
        yarn --frozen-lockfile
        cd eq-author
        yarn --frozen-lockfile
        yarn lint
        yarn test --coverage
        export percent=$(jq .total.lines.pct coverage/coverage-summary.json)
        echo "************************"
        echo "Coverage: $percent%"
        echo "************************"
        export result=$(echo "$percent > 90.00" | bc)
        exit $(( 1 - $result ))
    id: unit_tests
    entrypoint: /bin/bash
timeout: 1200s

