steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "compose"
      - "-feq-author-api/docker-compose-ci.yml"
      - up
      - "-d"
  - name: "node:14"
    env:
      - BABEL_ENV=test
      - NODE_ENV=test
      - PUBLIC_URL=test
      - CI=true
    args:
      - "-c"
      - |
        apt update
        apt install -y jq bc
        yarn --frozen-lockfile
        cd eq-author-api
        yarn --frozen-lockfile
        yarn lint
        yarn test:ci --coverage
    id: unit_tests
    entrypoint: /bin/bash
timeout: 1200s
