[build]
  base    = "eq-author"
  publish = "eq-author/build"
  command = 'sed -i -e "s/AUTHOR_API_URL_PLACEHOLDER/$AUTHOR_API_URL/g" ../netlify.toml && yarn build'

# A basic redirect rule
[[redirects]]
  from = "/signIn"
  to = "AUTHOR_API_URL_PLACEHOLDER/signIn"
  status = 200
[[redirects]]
  from = "/launch"
  to = "AUTHOR_API_URL_PLACEHOLDER/launch"
  status = 200
[[redirects]]
  from = "/graphql"
  to = "AUTHOR_API_URL_PLACEHOLDER/graphql"
  status = 200
