const ERR_EARLIEST_AFTER_LATEST = "ERR_EARLIEST_AFTER_LATEST";
const ERR_MAX_LENGTH_TOO_LARGE = "ERR_MAX_LENGTH_TOO_LARGE";
const ERR_MAX_LENGTH_TOO_SMALL = "ERR_MAX_LENGTH_TOO_SMALL";
const ERR_MAX_DURATION_TOO_SMALL = "ERR_MAX_DURATION_TOO_SMALL";
const ERR_MIN_DURATION_TOO_LARGE = "ERR_MIN_DURATION_TOO_LARGE";

module.exports = {
  ERR_EARLIEST_AFTER_LATEST,
  ERR_MAX_LENGTH_TOO_LARGE,
  ERR_MAX_LENGTH_TOO_SMALL,
  ERR_MAX_DURATION_TOO_SMALL,
  ERR_MIN_DURATION_TOO_LARGE,
};
