const ERR_EARLIEST_AFTER_LATEST = "ERR_EARLIEST_AFTER_LATEST";
const ERR_MAX_LENGTH_TOO_LARGE = "ERR_MAX_LENGTH_TOO_LARGE";
const ERR_MAX_LENGTH_TOO_SMALL = "ERR_MAX_LENGTH_TOO_SMALL";

module.exports = {
  ERR_EARLIEST_AFTER_LATEST,
  ERR_MAX_LENGTH_TOO_LARGE,
  ERR_MAX_LENGTH_TOO_SMALL,
};
