const ERR_EARLIEST_AFTER_LATEST = "ERR_EARLIEST_AFTER_LATEST";
const ERR_MAX_LENGTH_TOO_LARGE = "ERR_MAX_LENGTH_TOO_LARGE";
const ERR_MAX_LENGTH_TOO_SMALL = "ERR_MAX_LENGTH_TOO_SMALL";
const ERR_MAX_DURATION_TOO_SMALL = "ERR_MAX_DURATION_TOO_SMALL";
const ERR_ANSWER_NOT_SELECTED = "ERR_ANSWER_NOT_SELECTED";
const ERR_RIGHTSIDE_NO_VALUE = "ERR_RIGHTSIDE_NO_VALUE";
const ERR_RIGHTSIDE_AND_OR_NOT_ALLOWED = "ERR_RIGHTSIDE_AND_OR_NOT_ALLOWED";
const ERR_RIGHTSIDE_ALLOFF_OR_NOT_ALLOWED =
  "ERR_RIGHTSIDE_ALLOFF_OR_NOT_ALLOWED";
const DECIMAL_INCONSISTENCY = "ERR_REFERENCED_ANSWER_DECIMAL_INCONSISTENCY";

const ERR_PAGE_MOVED = "ERR_PAGE_MOVED";
const ERR_PAGE_DELETED = "ERR_PAGE_DELETED";
const ERR_SECTION_MOVED = "ERR_SECTION_MOVED";
const ERR_SECTION_DELETED = "ERR_SECTION_DELETED";

module.exports = {
  ERR_EARLIEST_AFTER_LATEST,
  ERR_MAX_LENGTH_TOO_LARGE,
  ERR_MAX_LENGTH_TOO_SMALL,
  ERR_MAX_DURATION_TOO_SMALL,
  ERR_ANSWER_NOT_SELECTED,
  ERR_RIGHTSIDE_NO_VALUE,
  ERR_RIGHTSIDE_AND_OR_NOT_ALLOWED,
  ERR_RIGHTSIDE_ALLOFF_OR_NOT_ALLOWED,
  DECIMAL_INCONSISTENCY,
  ERR_PAGE_MOVED,
  ERR_PAGE_DELETED,
  ERR_SECTION_MOVED,
  ERR_SECTION_DELETED,
};
