module.exports = [
  require("./questionnaire.json"),
  require("./definitions.json"),
  require("./section.json"),
  require("./folder.json"),
  require("./page.json"),
  require("./confirmationPage.json"),
  require("./answer.json"),
  require("./option.json"),
  require("./validation.json"),
  require("./logic.json"),
  require("./list.json"),
  require("./introduction.json"),
  require("./listCollectorPage.json"),
];
