module.exports = {
  ...require("./createQuestionnaire"),
  ...require("./deleteQuestionnaire"),
  ...require("./duplicateQuestionnaire"),
  ...require("./updateQuestionnaire"),
  ...require("./queryQuestionnaire"),
  ...require("./listQuestionnaires"),
  ...require("./publishQuestionnaire"),
  ...require("./reviewQuestionnaire"),
  ...require("./updatePreviewTheme"),
  ...require("./enableTheme"),
  ...require("./disableTheme"),
  ...require("./updateSurveyId"),
  ...require("./updateTheme"),
  ...require("./toggleQuestionnaireStarred"),
  ...require("./setQuestionnaireLocked"),
};
